- frontend/src/components/carousel/Carousel.css
- frontend/src/components/carousel/Carousel.jsx
- frontend/src/components/flip-card/FlipCard.jsx
- frontend/src/components/flip-card/flipCard.css
- frontend/src/components/sideBar/sideBar.module.css
- frontend/src/components/small-flip/SmallFlip.jsx
- frontend/src/components/small-flip/smallFlip.module.css
- frontend/src/pages/Landing/Home.js
- frontend/src/pages/Landing/home.css
> Carousel design

- frontend/src/App.js
- frontend/src/pages/Documents/AllDocumentsPage/DocumentsPage.js
- frontend/src/pages/Documents/NewDocumentPage/CreateNewDocumentPage.js
- frontend/src/pages/Documents/ProcessDocumentsPage/ProcessDocumentsPage.js
- frontend/src/pages/Documents/RejectedDocuments/RejectedDocumentsPage.js
- frontend/src/pages/Documents/SignDocumentPage/SignDocumentsPage.js
- frontend/src/pages/Notifications/NotificationsPage.js
- frontend/src/pages/Templates/AllTemplatesPage/TemplatesPage.js
- frontend/src/pages/Templates/ApproveTemplatesPage/ApproveTemplatesPage.js
- frontend/src/pages/Templates/CreateTemplatePage/CreateNewTemplatePage.js
- frontend/src/pages/Templates/RejectedTemplatesPage/RejectedTemplatesPage.js
- frontend/src/pages/Workflows/AllWorkflowsPage/WorkflowsPage.js
- frontend/src/pages/Workflows/ApproveWorkflowPage/ApproveWorkflowPage.js
- frontend/src/pages/Workflows/CreateNewWorkflowPage/CreateNewWorkflowPage.js
- frontend/src/pages/Workflows/RejectedWorkflowsPage/RejectedWorkflowsPage.js
Did the setup for routing to the necessary pages for the workflow app.
Please review and merge.
> Setup app with necessary routes

- app/urls.py
- app/views.py
I have make my changes on archive and archive_restore function. I also make changes on archive_restore url.
> mayorisaac

- app/views.py
Workflow_detail function updated
> updated workflow details

- app/processing.py
- app/urls.py
- app/views.py
Two new endpoints added and issues resolved
> New endpoint mayor

- app/helpers.py
@Couzy21 
Kindly find attached the fix for the document name
Thank you
> document name fix

- app/urls.py
- app/views.py
auth_viewer is added as param to fetch authenticated user data to notifications
pagination is added to different functions that fetch large datasets.
> pagination-added-mayorisaac

- app/helpers.py
- app/views.py
Hi @Couzy21 
Kindly find the latest changes here.
> Second Fix For the Template Name

- app/helpers.py
- app/views.py
I update the pagination. You can disregard if any other changes aside that:     
if dataset != None:
start = (page - 1) * limit
end = start + limit
return dataset[start:end]
return None
> pagination-updated-mayorisaac

- app/helpers.py
- app/views.py
removed pagination for reports_documents and reports_template endpoint and pagination function update
> code-updated-mayorisaac

- app/constants.py
- app/processing.py
Resolving the issue of staging site links being used in production process creation
@Couzy21
> production and staging process link

- app/urls.py
- app/views.py
endpoint added for Template and Documents reports metadata
> reports-mayorisaac

- app/helpers.py
- app/mongo_db_connection.py
- app/processing.py
- app/views.py
Update the clones metadata as the process moves on
> Update: document and clone metadata updates during processing

- app/urls.py
- app/views.py
@Couzy21 
Kindly find the code below
> API to insert template into metadata

- app/views.py
workflow update issue resolved and tested
> workflow update issue resolved and tested

- src/components/manageFiles/files/workflows/createWorkflows/CreateWorkflow.jsx
- src/components/newSidebar/Sidebar.jsx
- src/components/newSidebar/collapseItem/CollapseItem.jsx
- src/components/newSidebar/notifications/Notifications.jsx
- src/features/workflow/asyncTHunks.js
- src/httpCommon/httpCommon.js
- src/pages/App/WorkflowApp.js
- src/services/workflowServices.js
> Frontend fraol

- app/processing.py
fixed notification problem by updating metadata even when documentCloneMap already exists for that step
> Fixed notification issue

- app/views.py
workflowAi setting updated and tested
> workflowAi setting updated and tested

- app/helpers.py
- app/mongo_db_connection.py
- app/processing.py
- app/views.py
>  Update: Fixed notification bug successfully, metadata now updates

- app/urls.py
- app/views.py
Docusign Implemented and tested
> get_mobile_notifications_docusign

- src/components/hoverCard/documentCard/DocumentCard.jsx
> add collection id in payload

- src/components/hoverCard/documentCard/DocumentCard.jsx
> fix issue of collection id

- app/helpers.py
- app/mongo_db_connection.py
- app/views.py
Accepting a rejection message if a soc is rejected.
> message backend

- src/components/manageFiles/ProcessDetail/ProcessDetail.js
> fix process page issue

- app/helpers.py
- app/views.py
>  Process steps and removed process_members only

- src/App.js
- src/components/manageFiles/ProcessDetail/ProcessDetail.js
- src/components/manageFiles/ProcessDetail/StepDetail.js
- src/pages/Processes/AllProccessPage/ProcessesPage.js
Create Evaluation report new page
> Add active endpoint

- src/components/setWorkFlowInDocNew/steps/processDocument/ProcessDocument.jsx
> public id implementation

- src/App.js
- src/components/manageFiles/ProcessDetail/ProcessDetail.js
- src/components/manageFiles/ProcessDetail/StepDetail.js
- src/pages/Processes/AllProccessPage/ProcessesPage.js
show proper message if no data found for reports
> fix all issues on evaluation report page

- src/App.js
- src/components/manageFiles/ProcessDetail/DocumentDetailReport.js
- src/components/manageFiles/ProcessDetail/ProcessDetail.js
- src/components/manageFiles/ProcessDetail/ScaleDetailReport.js
- src/pages/Processes/AllProccessPage/ProcessesPage.js
- src/pages/Search/SearchPage.jsx
- src/utils/helpers.js
Add new report on the basis document
> add process detail document report

- src/components/manageFiles/ProcessDetail/ProcessDetail.js
- src/components/manageFiles/ProcessDetail/ScaleDetailReport.js
- src/components/newSidebar/collapseItem/CollapseItem.jsx
- src/utils/helpers.js
Fix process detail page load issue and create scales report component
> Fix process detail page load issue and create scales report component

- src/components/manageFiles/ProcessDetail/DocumentDetailReport.js
- src/components/manageFiles/ProcessDetail/ProcessDetail.js
- src/components/manageFiles/ProcessDetail/ProcessDetail.module.css
add and customize  UI of buttons and add payload on document report
> add and customize  UI of buttons and add payload on document report

- src/components/newSidebar/collapseItem/CollapseItem.jsx
- src/components/newSidebar/search/Search.jsx
- src/layouts/WorkflowLayout/WorkflowLayout.js
- src/pages/Search/SearchPage.jsx
- src/services/documentServices.js
fixed the route issue and added the org docs in the search
> updates on the search component and page

- src/components/hoverCard/documentCard/DocumentCard.jsx
- src/components/manageFiles/ProcessDetail/ProcessDetail.js
- src/components/manageFiles/ProcessDetail/ProcessDetail.module.css
- src/pages/Processes/AllProccessPage/ProcessesPage.js
fix reports button changes and add share button documentCard
> fix reports button changes and add share button documentCard

- src/components/manageFiles/sectionBox/SectionBox.jsx
- src/layouts/WorkflowLayout/WorkflowLayout.js
- src/pages/Folders/FoldersPage.jsx
- src/pages/Processes/AllProccessPage/ProcessesPage.js
add refresh button and sort data in folders page
> add refresh button and sort data in folders page

- app/helpers.py
- app/views.py
Bug fixed, please test, review and merge
> Bugfix: userlink pointing to the same document_map for user in multipe steps FIXED

- src/components/manageFiles/ProcessDetail/DocumentDetailReport.js
- src/components/manageFiles/ProcessDetail/ScaleDetailReport.js
- src/components/manageFiles/ProcessDetail/StepDetail.js
- src/components/newSidebar/Sidebar.jsx
- src/components/newSidebar/manageFile/ManageFile.jsx
- src/components/newSidebar/reports/Reports.jsx
- src/pages/Documents/AllDocumentsPage/DocumentsPage.js
- src/pages/Folders/modals/FoldersModal.jsx
- src/pages/Processes/AllProccessPage/ProcessesPage.js
- src/pages/Templates/AllTemplatesPage/TemplatesPage.js
fix sorting issue of pages and fix UI issue of process report page
> fix sorting issue of pages and fix UI issue of process report page

- app/helpers.py
- app/mongo_db_connection.py
- app/processing.py
- app/urls.py
- app/views.py
- wf_ai_core/settings.py
**Decoupled document processing method by separating the chunks responsible for "Assign Task" and "Request For Task"**
> Refactor doc processing

- src/components/manageFiles/files/documents/createDocument/createDocument.module.css
> fix the Dropdown UI Issues of the create document page

- app/helpers.py
- app/views_v2.py
Feature:  set documents ass private (with individual password)
> Feature:  set documents ass private (with individual password)

- app/processing.py
> Feature: Ability to skip process steps

- app/views_v2.py
> folder update

- app/views_v2.py
Reject entire process on single document rejection && revert changes to document state and process state if an error occurs
> Update: reject entire process on single document rejection

- src/components/manageFiles/files/documents/createDocument/createDocument.module.css
- src/components/newSidebar/notifications/notification.module.css
- src/pages/Folders/modals/folders_modal.module.css
I added the UI of the application
> Update Changes for UI

- app/helpers.py
- app/processing.py
- app/views_v2.py
Ability to create and run internal processes. However, support for this feature is limited at this time to **only ONE** user in the step where the **internal process** is created
> New Feature: Internal processing

- src/components/manageFiles/sectionBox/SectionBox.jsx
changed card items from 10 to 12
> changed card items from 10 to 12

- app/views.py
- app/views_v2.py
Fixed the document content problem
> Bugfix: Fixed document content issue

- src/components/manageFiles/files/workflows/createWorkflows/createWorkflow.module.css
- src/components/setWorkFlowInDocNew/steps/connectWebflowToDoc/contents/selectMembersToAssign/CreateGroup/CreateGroup.jsx
- src/components/setWorkFlowInDocNew/steps/connectWebflowToDoc/contents/selectMembersToAssign/SelectMembersToAssign.jsx
> Update the process page
